### ISSUE TITLE
thanks & suggestions for elix promotion

### ISSUE THREAD

**Issue by geonanorch** [elix/elix.org#30]
Wow... I spent several hours looking for a lightweight, modular, complete and unopiniated (understand: easily stylable) UI component library and almost did not find elix! Thank you very much for this awesome package, in my opinion elix deserves to me a lot more popular!

Which brings me to the main reason for this issue (though thanking you would already be reason enough): I spotted several things, which might deter potential users (just my opinion of course).

1. the "getting started" link could be more prominent, I actually oversaw it at first. Imho there should be a button at least as big as the "The Elix Vision" one.

2. the "getting Javascript instantiation paragraph could include explicitly the use case define-from-javascript-and-use-in-html, which I think is the main one. It is obvious to anymore who has worked with web components before, but not to a newcomer.

3. people want to see the potential of the library at first glance. On the main page the components are shown, but
- when clicking on them there is not always a demo (example: button)
- it would be very sexy if a user could access a demo page will all components and select from a list of themes (e.g. minimal/default, material, etc...) to illustrate how flexible elix is

I knew what I was looking for and I am very happy to use Elix as it is, just sending you this feedback as someone with a fresh view in case it can help with the promotion of the project. At any rate thanks again!

**Comment by JanMiksovsky** [comment]
Thanks for the nice words and for your thoughtful feedback!

Your point about the Getting Started link is well taken. I did a quick experiment to try placing a button alongside the existing Vision button, but it's going to take a better more design finesse to get a result that works well.

I've moved all these ideas over to our internal To Do list for the site. We have a lot of priorities to balance, so it might be a while before we can lavish more attention on the Elix top page again, but I'm hoping we can get to some of this soon.

**Comment by JanMiksovsky** [comment]
Oh, also just wanted to mention that I'd kind of forgotten about this specific repo. For the last few years, we've built the Elix documentation as part of our company site, which is maintained in a private repo. So this elix.org repo is no longer active — if you see other issues with the site or Elix itself, please file issues on the main Elix repo at https://github.com/elix/elix.

We should probably make this old repo private at some point. Sorry for any confusion.

**Comment by geonanorch** [comment]
Duly noted, all further input through elix/elix, and thank you for considering the present input.

Regarding the 'getting started' button, why not in the header menu replacing 'Elix Components' (which is kind of redundant when already on that page) or else floating right within the green 'Elix' banner below the menu? Just a thought, will leave you in peace now.

Thanks again, I wish component kitchen all the best!
